banking_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('loans/', include('loans.urls', namespace='loans')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# print("urlpatterns", urlpatterns)

home/urls.py
from django.urls import path
from .views import HomeView, About

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home_view'),
    path('about/', About.as_view(), name='about'),

]

loans/urls.py
from django.urls import path
from .views import ApplyLoan, LoanStatus
from django.contrib.auth.decorators import login_required

app_name = 'loans'

urlpatterns = [
    path('loan_form/', login_required(ApplyLoan.as_view()), name='loan_form'),
    path('loan_status/', login_required(LoanStatus.as_view()), name='loan_status'),
]

transactions/urls.py
from django.urls import path
from .views import DepositView, WithdrawalView, SendOtpView, CheckOtpView, TransactionsView, InterestView, \
    MoneyTransferView, AddPayeeView
from django.contrib.auth.decorators import login_required

app_name = 'transactions'
urlpatterns = [
    path('deposit/', login_required(DepositView.as_view()), name='deposit'),
    path('withdrawal/', login_required(WithdrawalView.as_view()), name='withdrawal'),
    path('send_otp/', login_required(SendOtpView.as_view()), name='send_otp'),
    path('check_otp/', login_required(CheckOtpView.as_view()), name='check_otp'),
    path('transaction_details/', login_required(TransactionsView.as_view()), name='transaction_details'),
    path('interest_details/', login_required(InterestView.as_view()), name='interest_details'),
    path('money_transfer', login_required(MoneyTransferView.as_view()), name='money_transfer'),
    path('add_payee', login_required(AddPayeeView.as_view()), name='add_payee')

]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from .managers import UserManager


class User(AbstractUser):
    username = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    contact_no = models.CharField(max_length=12, unique=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    # It is a built-in decorator it  help in defining the properties effortlessly without manually calling the inbuilt function property().
    # It return the property attributes of a class from the stated getter, setter and deleter as parameters.
    @property
    def account_no(self):
        if hasattr(self, 'account'):
            # here hasattr() checking for the existence of an attribute, if TRUE then returning it.
            return self.account.account_no
        return None

    def address(self):
        if hasattr(self, 'address'):
            # here hasattr() checking for the existence of an attribute, if TRUE then returning it.
            return self.address
        return None

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return None

    @property
    def full_address(self):
        if hasattr(self, 'address'):
            return '{}, {}-{}, {}'.format(
                self.address.street_address,
                self.address.district,
                self.address.postal_code,
                self.address.state,
            )
        return None


class AccountDetails(models.Model):
    GENDER_CHOICE = (
        ("M", "Male"),
        ("F", "Female"),
    )
    ACCOUNT_CHOICE = (
        ("C", "Current"),
        ("S", "Saving"),
    )

    user = models.OneToOneField(User, related_name='account', on_delete=models.CASCADE)
    account_no = models.PositiveIntegerField(
        unique=True,
        validators=[
            MinValueValidator(10000000),
            MaxValueValidator(99999999)
        ]
    )
    # hexstr = secrets.token_hex(3)
    # account_no = models.CharField(int(hexstr, 16),)

    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    ifsc_code = models.CharField(max_length=30, default='RK012345')
    account_type = models.CharField(max_length=1, choices=ACCOUNT_CHOICE)
    birth_date = models.DateField(help_text="Date format must be YYYY-MM-DD")
    balance = models.DecimalField(default=1000, max_digits=12, decimal_places=2)
    picture = models.ImageField(null=True, blank=True, upload_to='profile/', default='profile/dummy-image.jpg')

    def __str__(self):
        return str(self.account_no)


class State(models.Model):
    state_name = models.CharField(max_length=50)

    def __str__(self):
        return self.state_name


class District(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    district_name = models.CharField(max_length=50)

    def __str__(self):
        return self.district_name


class Branch(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    branch_name = models.CharField(max_length=50)

    def __str__(self):
        return self.branch_name


class AddressDetails(models.Model):
    user = models.OneToOneField(User, related_name='address', on_delete=models.CASCADE)
    street_address = models.CharField(max_length=512)
    postal_code = models.CharField(max_length=6)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    branch_name = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.id

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from django.views import View


class HomeView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, "home/home.html")
        else:
            return redirect("user_profile")


class About(View):
    def get(self, request):
        return render(request, "home/about.html")

home/templates/home/about.html
{% extends 'home/base.html' %}
{% block title %} About | {{ block.super }}{% endblock title %}
{% block content %}
<h1>About US</h1>
<hr>
<p>This Bank System is simple, least but best features web application developed for learning purpose not for any organisation.</p>
<p> It is fully designed by using Django framework of python.</p>
<p>In this, I have used many libraries like celery for Interest calculation etc.</p>
<hr>
{% endblock content %}

home/templates/home/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title%} Banking System {% endblock title %}</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    {% include "home/navbar.html" %}
    <div class="container" style="padding-top: 60px;">

    {% block content %}

    {% endblock content %}

    </div>
    {% include "home/footer.html" %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.slim.js" integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block script_content %}

    {% endblock script_content %}

  </body>
</html>

home/templates/home/footer.html
<hr>
<footer class="footer bg-gray-200 relative pt-1 border-b-2 mt-10">
    <div class="container mx-auto px-6">
        <div class="mt-5 flex flex-col items-center">
            <div class="sm:w-2/3 text-center py-6">
                <p class="text-md text-gray-900 font-bold mb-2">
{#                    © 2022  <a href="#" target="_blank">Design & Developed by Rakesh Kumar</a>#}
                    © Copyright 2022. All rights reserved. Developed by RAKESH KUMAR.

                </p>
            </div>
        </div>
    </div>
</footer>

home/templates/home/home.html
{% extends 'home/base.html' %}

{% block title %} {{ block.super }}{{request.user.is_authenticated}}{% endblock title %}

{% block content %}
<div class="container" style="padding-top: 50px;">
<div class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Welcome to the RK Banking System</h1>
        <hr>
        <p class="lead text-muted"></p>
        <p>
          <h1 style="font-size: 12rem" class="font-black text-gray-800">🙏₹₹₹🙏</h1>
        </p>
      </div>
</div>
</div>

{% endblock content %}

home/templates/home/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

home/templates/home/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home:home_view' %}">Banking System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'home:home_view' %}">Home</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'user_profile' %}">Your Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'transactions:deposit' %}">Deposit</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'transactions:transaction_details' %}">Transactions</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'transactions:interest_details' %}">Interest</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'transactions:money_transfer' %}">Money Transfer</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'loans:loan_form' %}">Loan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home:about' %}">About Us</a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}" class="btn btn-danger btn-sm" type="button">Logout</a>
        {% else %}
            <a href="{% url 'login' %}" class="btn btn-success btn-sm" type="button">Login Account</a> ||
            <a href="{% url 'register' %}" class="btn btn-primary btn-sm" type="button">Create an Account</a>
        {% endif %}
    </form>
  </div>
</nav>

home/templates/home/transactions.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "home/messages.html" %}

<div class="page-header">
  <h1 class="text-center"><b>Banking System</b><br><small>RK Bank.</small></h1>
</div>

<div class="row">
  <div class="col-xs-12 col-md-8 text-left">
      <p><img src="{{ profile.picture.url }}" alt="Profile Picture" width="100" height="100" class=""rounded-circle article-img></p>
      <h4><b>Account Name: </b>{{ user.full_name }}</h4>
      <h4><b>Contact No: </b>{{ user.contact_no }}</h4>
      <h4><b>Email Address: </b>{{ user.email }} </h4>
      <h4><b>Date of Birth: </b>{{ user.account.birth_date }}</h4>
      <h4><b>Gender: </b>{{ user.account.get_gender_display }}</h4>
      <h4><b>Address: </b>{{ user.full_address }}</h4>
      <a class="btn btn-primary" href="{% url 'user_update' user.id %}">Edit User details</a>
      <a class="btn btn-primary" href="{% url 'account_update' user.account.id %}">Edit User Account details</a>
      <a class="btn btn-primary" href="{% url 'address_update' user.address.id %}">Edit User Address details</a>
  </div>
  <div class="col-xs-6 col-md-4 text-left">
    <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
      <h4><b>Account Type: </b>{{ user.account.get_account_type_display }}</h4>
      <h4><b>Branch Name: </b>{{ user.account.get_branch_name_display }}</h4>

    <h4><b>Account No: </b>{{ user.account_no }}</h4><br><br>
    <div class="well">
    <h4 class="card"><b>Account Balance: </b>₹{{ user.balance }}</h4>
    <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
    <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
    </div>
  </div>
</div>
<hr>

{% endblock content %}