accounts/urls.py
from django.urls import path
from .views import RegisterView, LoginView, UserUpdateView, UserAccountUpdateView, UserAddressUpdateView, ProfileView, \
    LoadDistrictsView, LoadBranchView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('user_profile', login_required(ProfileView.as_view()), name='user_profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='home/home.html'), name='logout'),
    path('user_update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('account_update/<int:pk>/', UserAccountUpdateView.as_view(), name='account_update'),
    path('address_update/<int:pk>/', UserAddressUpdateView.as_view(), name='address_update'),
    path('load_districts/', LoadDistrictsView.as_view(), name='load_districts'),
    path('load_branches/', LoadBranchView.as_view(), name='load_branches'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('loans/', include('loans.urls', namespace='loans')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# print("urlpatterns", urlpatterns)

home/urls.py
from django.urls import path
from .views import HomeView, About

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home_view'),
    path('about/', About.as_view(), name='about'),

]

transactions/urls.py
from django.urls import path
from .views import DepositView, WithdrawalView, SendOtpView, CheckOtpView, TransactionsView, InterestView, \
    MoneyTransferView, AddPayeeView
from django.contrib.auth.decorators import login_required

app_name = 'transactions'
urlpatterns = [
    path('deposit/', login_required(DepositView.as_view()), name='deposit'),
    path('withdrawal/', login_required(WithdrawalView.as_view()), name='withdrawal'),
    path('send_otp/', login_required(SendOtpView.as_view()), name='send_otp'),
    path('check_otp/', login_required(CheckOtpView.as_view()), name='check_otp'),
    path('transaction_details/', login_required(TransactionsView.as_view()), name='transaction_details'),
    path('interest_details/', login_required(InterestView.as_view()), name='interest_details'),
    path('money_transfer', login_required(MoneyTransferView.as_view()), name='money_transfer'),
    path('add_payee', login_required(AddPayeeView.as_view()), name='add_payee')

]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from .managers import UserManager


class User(AbstractUser):
    username = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    contact_no = models.CharField(max_length=12, unique=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    # It is a built-in decorator it  help in defining the properties effortlessly without manually calling the inbuilt function property().
    # It return the property attributes of a class from the stated getter, setter and deleter as parameters.
    @property
    def account_no(self):
        if hasattr(self, 'account'):
            # here hasattr() checking for the existence of an attribute, if TRUE then returning it.
            return self.account.account_no
        return None

    def address(self):
        if hasattr(self, 'address'):
            # here hasattr() checking for the existence of an attribute, if TRUE then returning it.
            return self.address
        return None

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return None

    @property
    def full_address(self):
        if hasattr(self, 'address'):
            return '{}, {}-{}, {}'.format(
                self.address.street_address,
                self.address.district,
                self.address.postal_code,
                self.address.state,
            )
        return None


class AccountDetails(models.Model):
    GENDER_CHOICE = (
        ("M", "Male"),
        ("F", "Female"),
    )
    ACCOUNT_CHOICE = (
        ("C", "Current"),
        ("S", "Saving"),
    )

    user = models.OneToOneField(User, related_name='account', on_delete=models.CASCADE)
    account_no = models.PositiveIntegerField(
        unique=True,
        validators=[
            MinValueValidator(10000000),
            MaxValueValidator(99999999)
        ]
    )
    # hexstr = secrets.token_hex(3)
    # account_no = models.CharField(int(hexstr, 16),)

    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    ifsc_code = models.CharField(max_length=30, default='RK012345')
    account_type = models.CharField(max_length=1, choices=ACCOUNT_CHOICE)
    birth_date = models.DateField(help_text="Date format must be YYYY-MM-DD")
    balance = models.DecimalField(default=1000, max_digits=12, decimal_places=2)
    picture = models.ImageField(null=True, blank=True, upload_to='profile/', default='profile/dummy-image.jpg')

    def __str__(self):
        return str(self.account_no)


class State(models.Model):
    state_name = models.CharField(max_length=50)

    def __str__(self):
        return self.state_name


class District(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    district_name = models.CharField(max_length=50)

    def __str__(self):
        return self.district_name


class Branch(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    branch_name = models.CharField(max_length=50)

    def __str__(self):
        return self.branch_name


class AddressDetails(models.Model):
    user = models.OneToOneField(User, related_name='address', on_delete=models.CASCADE)
    street_address = models.CharField(max_length=512)
    postal_code = models.CharField(max_length=6)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    branch_name = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.id

accounts/forms.py
from .models import User, AccountDetails, AddressDetails, District
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "contact_no",
            "password1",
            "password2"
        ]


class AccountDetailsForm(forms.ModelForm):
    class Meta:
        model = AccountDetails
        fields = [
            'account_type',
            'gender',
            'birth_date',
            'picture'
        ]


class AddressDetailsForm(forms.ModelForm):
    class Meta:
        model = AddressDetails
        fields = [
            'street_address',
            'postal_code',
            'state',
            'district',
            'branch_name',
        ]

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['district'].queryset = District.objects.none()

            if 'state' in self.data:
                try:
                    state_id = int(self.data.get('state'))
                    self.fields['districts'].queryset = District.objects.filter(state_id=state_id).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
            elif self.instance.pk:
                self.fields['district'].queryset = self.instance.state.district_set.order_by('name')


class UserLoginForm(forms.Form):
    account_no = forms.IntegerField(label="Account Number")
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        account_no = self.cleaned_data.get("account_no")
        password = self.cleaned_data.get("password")

        if account_no and password:
            user = authenticate(account_no=account_no, password=password)
            if not user:
                raise forms.ValidationError("Login Credentials is not Valid")
            if not user.check_password(password):
                raise forms.ValidationError("Password Does not Match.")
            if not user.is_active:
                raise forms.ValidationError("Account is not Active.")

        return super(UserLoginForm, self).clean(*args, **kwargs)

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
from django.shortcuts import render, redirect
from accounts import forms
from django.views import View
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User, District, Branch, AccountDetails, AddressDetails


class RegisterView(View):
    def get(self, request):
        # here creating a register form with register_view function.
        if request.user.is_authenticated:
            return redirect("user_profile")
        else:
            user_form = forms.UserRegistrationForm()
            account_form = forms.AccountDetailsForm()
            address_form = forms.AddressDetailsForm()

            context = {
                "title": "Create a Bank Account",
                "user_form": user_form,
                "account_form": account_form,
                "address_form": address_form,
            }
            return render(request, "accounts/register_form.html", context)

    def post(self, request):
        user_form = forms.UserRegistrationForm(request.POST or None, )
        account_form = forms.AccountDetailsForm(request.POST or None, request.FILES or None)
        address_form = forms.AddressDetailsForm(request.POST or None)

        if user_form.is_valid() and account_form.is_valid() and address_form.is_valid():
            # here I am getting most of model data from a form,
            # but I need to populate some null=False fields with non-form data.
            user_details = user_form.save(commit=False)
            account_details = account_form.save(commit=False)
            address_details = address_form.save(commit=False)
            password = user_form.cleaned_data.get("password1")
            user_details.set_password(password)
            user_details.save()
            account_details.user = user_details
            account_details.save()
            address_details.user = user_details
            address_details.save()
            new_user = authenticate(account_no=user_details.account_no, password=password)
            login(request, new_user)

            messages.success(request, '''Thank You For Creating A Bank Account {}.
                Your Account Number is {}, Please use this number to login
                '''.format(new_user.full_name, new_user.account_no))
            return redirect("user_profile")

        context = {
            "title": "Create a Bank Account",
            "user_form": user_form,
            "account_form": account_form,
            "address_form": address_form,
        }
        return render(request, "accounts/register_form.html", context)


class LoadDistrictsView(View):
    def get(self, request):
        state_id = request.GET.get('state_id')
        districts = District.objects.filter(state_id=state_id).order_by('district_name')
        filtered_districts = {district.id: district.district_name for district in districts}
        return JsonResponse(filtered_districts)


class LoadBranchView(View):
    def get(self, request):
        district_id = request.GET.get('district_id')
        branches = Branch.objects.filter(district_id=district_id).order_by('branch_name')
        filtered_branches = {branch.id: branch.branch_name for branch in branches}
        return JsonResponse(filtered_branches)


class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect("user_profile")
        else:
            form = forms.UserLoginForm()
            context = {"form": form,
                       "title": "Load Account Details via Login",
                       }
            return render(request, "accounts/login_form.html", context)

    def post(self, request):
        form = forms.UserLoginForm(request.POST)
        if form.is_valid():
            account_no = form.cleaned_data.get("account_no")
            password = form.cleaned_data.get("password")
            # authenticate with Account No & Password
            user = authenticate(account_no=account_no, password=password)
            login(request, user)
            messages.success(request, 'Welcome, {}!'.format(user.full_name))
            return redirect("user_profile")

        return render(request, "accounts/login_form.html", {'form': form})


class ProfileView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, "home/home.html")
        else:
            user = request.user
            return render(request, "accounts/account_info.html", {"user": user})


# From here Updating all the fields related to account details......................
class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    success_message = 'User Updated Successfully!'
    fields = ['email', 'contact_no']
    success_url = '/'


class UserAccountUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = AccountDetails
    success_message = 'Account Details Updated Successfully!'
    fields = [
        'account_type',
        'gender',
        'birth_date',
        'picture'
    ]
    success_url = '/'


class UserAddressUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = AddressDetails
    success_message = 'User Address Updated Successfully!'
    fields = [
        'state',
        'district',
        'branch_name',
        'street_address',
        'postal_code',
    ]
    success_url = '/'

accounts/templates/accounts/account_info.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "home/messages.html" %}

<div class="page-header">
    <h3 class="text-center">RK Bank</h3>
</div>

<div class="row">
    <div class="col-xs-12 col-md-8 text-left">
        <p><img src="{{ user.account.picture.url }}" alt="Profile Picture" width="100" height="100" class=""
                rounded-circle article-img></p>
        <h4><b>Account Name: </b>{{ user.full_name }}</h4>
        <h4><b>Contact No: </b>{{ user.contact_no }}</h4>
        <h4><b>Email Address: </b>{{ user.email }} </h4>
        <h4><b>Date of Birth: </b>{{ user.account.birth_date }}</h4>
        <h4><b>Gender: </b>{{ user.account.get_gender_display }}</h4>
        <h4><b>Address: </b>{{ user.full_address }}</h4>
        <a class="btn btn-primary" href="{% url 'user_update' user.id %}">Edit User details</a>
        <a class="btn btn-primary" href="{% url 'account_update' user.account.id %}">Edit User Account details</a>


    </div>
    <div class="col-xs-6 col-md-4 text-left">
        <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
        <h4><b>Account Type: </b>{{ user.account.get_account_type_display }}</h4>
        <h4><b>Branch Name: </b>{{ user.account.get_branch_name_display }}</h4>

        <h4><b>Account No: </b>{{ user.account_no }}</h4><br><br>
        <div class="well">
            <h4 class="card"><b>Account Balance: </b>₹{{ user.balance }}</h4>
            <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
            <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
        </div>
    </div>
</div>
<hr>
{% endblock content %}

accounts/templates/accounts/accountdetails_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
{% include "home/messages.html" %}
<h2>{{ title }}</h2><hr>
<form method="POST" action="" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-success" type="submit" value='Update all Fields'>

</form>

{% endblock content %}

accounts/templates/accounts/addressdetails_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
{% include "home/messages.html" %}
<h2>{{ title }}</h2><hr>
<form method="POST" action="" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-success" type="submit" value='Update all Fields'>

</form>

{% endblock content %}

accounts/templates/accounts/login_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
<div class="content-section">
    {% include "home/messages.html" %}
    <h2>{{ title }}</h2><hr>
    <form method="POST" action="" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <div class="form-group">
            <input class="btn btn-success" type="submit" value='Login'>
            <small class="text-muted ml-2">
                <a href="{% url 'password_reset' %}"><b>Forgot Password?</b></a>
            </small>
            <br>
            <div class="border-top pt-3">
                <small class="text-muted ml-2">
                    <b>You have not an Account?</b><a class="ml-2" href="{% url 'register' %}">Open An Account</a>
                </small>
            </div>
        </div>

    </form>

</div>
{% endblock content %}

accounts/templates/accounts/password_reset.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'login' %}">Sign In Here</a>
{% endblock content %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

accounts/templates/accounts/password_reset_done.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock content %}

accounts/templates/accounts/register_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
{% include "home/messages.html" %}
    <h2>{{ title }}</h2><hr>
    <form method="POST" action="" id= "registerForm"  novalidate enctype='multipart/form-data'>
        {% csrf_token %}
        <table>
            {{ user_form|crispy }}
            {{ address_form|crispy }}
            {{ account_form|crispy }}
        </table>
        <br>
        <input class="btn btn-success" type="submit" value='Open an Account'>
        <small class="text-muted">
            <b>You have already an Account?</b><a class="ml-2" href="{% url 'login' %}">Login An Account</a>
        </small>
    </form>
{% endblock content %}

{% block script_content %}
<script>
     $("#id_state").change(function () {
        let state_id = $(this).val();  // get the selected state ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: '{% url "load_districts" %}',  // set the url of the request (= localhost:8000/account/ajax/load-districts/)
            method:"GET",
            data: {
                'state_id': state_id       // add the state id to the GET parameters
            },
            success: function (district_list) {   // `data` is the return of the `load_districts` view function
                $('#id_district').empty();
                $.each(district_list, function(key, value) {
                    $('#id_district')
                         .append($("<option></option>")
                                    .attr("value", key)
                                    .text(value));
                });
                // $("#id_district").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });
    });

      $("#id_district").change(function () {
        let district_id = $(this).val();  // get the selected state ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: '{% url "load_branches" %}',  // set the url of the request (= localhost:8000/account/ajax/load-districts/)
            method:"GET",
            data: {
                'district_id': district_id       // add the state id to the GET parameters
            },
            success: function (branch_list) {   // `data` is the return of the `load_districts` view function
                $('#id_branch_name').empty();
                $.each(branch_list, function(key, value) {
                    $('#id_branch_name')
                         .append($("<option></option>")
                                    .attr("value", key)
                                    .text(value));
                });
                // $("#id_district").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });
    });
</script>
{% endblock script_content %}

accounts/templates/accounts/user_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
{% include "home/messages.html" %}
<h2>{{ title }}</h2><hr>
<form method="POST" action="" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-success" type="submit" value='Update all Fields'>

</form>

{% endblock content %}

accounts/templates/accounts/useraddress_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
{% include "home/messages.html" %}
<h2>{{ title }}</h2><hr>
<form method="POST" action="" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-success" type="submit" value='Update all Fields'>

</form>

{% endblock content %}