banking_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('loans/', include('loans.urls', namespace='loans')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# print("urlpatterns", urlpatterns)

home/urls.py
from django.urls import path
from .views import HomeView, About

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home_view'),
    path('about/', About.as_view(), name='about'),

]

transactions/urls.py
from django.urls import path
from .views import DepositView, WithdrawalView, SendOtpView, CheckOtpView, TransactionsView, InterestView, \
    MoneyTransferView, AddPayeeView
from django.contrib.auth.decorators import login_required

app_name = 'transactions'
urlpatterns = [
    path('deposit/', login_required(DepositView.as_view()), name='deposit'),
    path('withdrawal/', login_required(WithdrawalView.as_view()), name='withdrawal'),
    path('send_otp/', login_required(SendOtpView.as_view()), name='send_otp'),
    path('check_otp/', login_required(CheckOtpView.as_view()), name='check_otp'),
    path('transaction_details/', login_required(TransactionsView.as_view()), name='transaction_details'),
    path('interest_details/', login_required(InterestView.as_view()), name='interest_details'),
    path('money_transfer', login_required(MoneyTransferView.as_view()), name='money_transfer'),
    path('add_payee', login_required(AddPayeeView.as_view()), name='add_payee')

]

transactions/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings
from django.core.validators import MinValueValidator

User = settings.AUTH_USER_MODEL


class Deposit(models.Model):
    user = models.ForeignKey(
        User,
        related_name='deposits',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12,
        validators=[
            MinValueValidator(Decimal('10.00'))
        ]
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    status = models.CharField(default="credited", max_length=40)

    def __str__(self):
        return f"{str(self.user)}: {self.amount}"


class Withdrawal(models.Model):
    user = models.ForeignKey(
        User,
        related_name='withdrawals',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12,
        validators=[
            MinValueValidator(Decimal('10.00'))
        ]
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    status = models.CharField(default="debited", max_length=40)

    def __str__(self):
        return f"{str(self.user)}: {self.amount}"


class WithdrawalOtp(models.Model):
    user = models.ForeignKey(
        User,
        related_name='otpauth',
        on_delete=models.CASCADE,
    )
    otp = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{str(self.user)}: {self.otp}"


class Interest(models.Model):
    user = models.ForeignKey(
        User,
        related_name='interests',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12,
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(default="Interest Credited", max_length=40)

    def __str__(self):
        return str(self.user)


class PayeeDetails(models.Model):
    user = models.ForeignKey(
        User,
        related_name='payee',
        on_delete=models.CASCADE,
    )
    payee_account = models.CharField(max_length=20)
    payee_ifsc = models.CharField(max_length=30)

    def __str__(self):
        return self.payee_account

transactions/forms.py
from django import forms
from .models import Deposit, Withdrawal

class DepositForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = ["amount"]

class WithdrawalForm(forms.ModelForm):
    class Meta:
        model = Withdrawal
        fields = ["amount"]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        # if kwargs has no key 'user', user is assigned None
        super(WithdrawalForm, self).__init__(*args, **kwargs)

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if self.user.account.balance < amount:
            raise forms.ValidationError('You Can Not Withdraw More Than You Balance.')
        return amount

transactions/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from django.core.paginator import Paginator
from .forms import DepositForm, WithdrawalForm
from .models import WithdrawalOtp, PayeeDetails
from accounts.models import AccountDetails, User
from .tasks import send_mail_task
from django.db.models import Sum
from itertools import chain
from transactions.models import Deposit, Withdrawal, Interest


class DepositView(View):
    def get(self, request):
        form = DepositForm()
        return render(request, "transactions/deposit_form.html", {"form": form})

    def post(self, request):
        form = DepositForm(request.POST or None)
        if form.is_valid():
            deposit = form.save(commit=False)
            deposit.user = request.user
            deposit.save()
            deposit.user.account.balance += deposit.amount
            deposit.user.account.save()
            messages.success(request, 'You Have Deposited ₹ {}.'.format(deposit.amount))
            return redirect("user_profile")
        return render(request, 'transactions/deposit_form.html', {'form': form})


class WithdrawalView(View):
    def get(self, request):
        form = WithdrawalForm()
        return render(request, "transactions/withdraw_form.html", {"form": form})

    def post(self, request):
        form = WithdrawalForm(request.POST or None, user=request.user)
        if form.is_valid():
            withdrawal = form.save(commit=False)
            withdrawal.user = request.user
            withdrawal.save()
            # subtracting users withdrawal from balance.
            withdrawal.user.account.balance -= withdrawal.amount
            withdrawal.user.account.save()
            messages.success(request, 'You Have Withdrawn ₹ {}.'.format(withdrawal.amount))
            return redirect("user_profile")
        else:
            return render(request, 'transactions/withdraw_form.html', {'form': form})


class SendOtpView(View):
    def get(self, request):
        send_otp = send_mail_task(request.user)
        otp_obj, created = WithdrawalOtp.objects.get_or_create(user_id=request.user.id)
        otp_obj.otp = send_otp
        ack = otp_obj.save()
        if ack is None:
            return JsonResponse({'status': 1})
        else:
            return JsonResponse({'status': 0})


class CheckOtpView(View):
    def get(self, request):
        send_otp = WithdrawalOtp.objects.filter(user_id=request.user.id)
        if send_otp[0].otp == int(request.GET.get('otp')):
            return JsonResponse({'status': 1})
        else:
            return JsonResponse({'status': 0})


class TransactionsView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, "home/home.html")
        else:
            user = request.user
            deposit_list = Deposit.objects.filter(user=user)
            deposit_sum = deposit_list.aggregate(Sum('amount'))['amount__sum']
            withdrawal_list = Withdrawal.objects.filter(user=user)
            withdrawal_sum = withdrawal_list.aggregate(Sum('amount'))['amount__sum']
            transaction_list = sorted(chain(deposit_list, withdrawal_list), key=lambda instance: instance.timestamp)
            paginator = Paginator(transaction_list, 5)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            context = {
                "user": user,
                "deposit_sum": deposit_sum,
                "withdrawal_sum": withdrawal_sum,
                "page_obj": page_obj
            }
            return render(request, "transactions/account_transaction.html", context)


class InterestView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, "home/home.html")
        else:
            user = request.user
            interest_list = Interest.objects.filter(user=user)
            interest_sum = interest_list.aggregate(Sum('amount'))['amount__sum']
            # interest_list = sorted(interest_list)
            paginator = Paginator(interest_list, 5)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            context = {
                "user": user,
                "interest_sum": interest_sum,
                "page_obj": page_obj
            }
            return render(request, "transactions/account_interest.html", context)


class MoneyTransferView(View):
    def get(self, request):
        try:
            payee_list = PayeeDetails.objects.all().exclude(payee_account=request.user.account.account_no)
        except PayeeDetails.DoestNotExist:
            payee_list = None
        finally:
            return render(request, 'money_transfer/money_transfer_form.html', {'payee_list': payee_list})

    def post(self, request):
        print(f"REQUEST{request.POST}")
        payee_details = PayeeDetails.objects.get(id=request.POST.get('payee_id'))
        # from Selected payee_id, i got payee's bank account.
        payee = AccountDetails.objects.get(account_no=payee_details.payee_account)
        # from payee's bank account i got his/her balance by obj payee obj
        payer = AccountDetails.objects.get(account_no=request.user.account.account_no)
        # Creating Payer obj for manipulation balance. like subtract amt..
        if request.POST.get('mode') == '1':
            users = User.objects.filter(account__balance__isnull=False)
            # mode 1 is IMPS and mode 2 is NEFT
            send_amt = float(request.POST.get('send_amt'))
            if float(send_amt + send_amt * 0.10) <= float(payer.balance):
                payer.balance -= int(
                    float(request.POST.get('send_amt')) + float(float(request.POST.get('send_amt')) * 0.10))
                payer.save()
                payee.balance += int(request.POST.get('send_amt'))
                payee.save()
                payer_withdrawal = Withdrawal(amount=send_amt, user_id=request.user.id)
                payer_withdrawal.save()
                payee_withdrawal = Deposit(amount=send_amt, user_id=payee_details.user_id)
                payee_withdrawal.save()
                messages.success(request,
                                 f'Amount ₹ {send_amt} Successfully transferred to Account no {payee_details.payee_account}')
                return redirect("user_profile")
            else:
                messages.error(request, 'Sorry, Your Account have not sufficient balance to transfer of this amount')
                return redirect("user_profile")

        elif request.POST.get('mode') == '2':
            send_amt = float(request.POST.get('send_amt'))

            if float(send_amt + send_amt * 0.05) <= float(payer.balance):
                payer.balance -= int(
                    float(request.POST.get('send_amt')) + float(float(request.POST.get('send_amt')) * 0.05))
                payer.save()
                payee.balance += int(request.POST.get('send_amt'))
                payee.save()
                payer_withdrawal = Withdrawal(amount=send_amt, user_id=request.user.id)
                payer_withdrawal.save()
                payee_withdrawal = Deposit(amount=send_amt, user_id=payee_details.user_id)
                payee_withdrawal.save()
                messages.success(request,
                                 f'Amount ₹ {send_amt} Successfully transferred to Account no {payee_details.payee_account} ')
                return redirect("user_profile")
            else:
                messages.error(request, 'Sorry, Your Account have not sufficient balance to transfer of this amount')
                return redirect("user_profile")


class AddPayeeView(View):
    def get(self, request):
        payee_ac = PayeeDetails.objects.values('payee_account')
        account_list = AccountDetails.objects.values('id', 'account_no', 'ifsc_code')
        for payee in payee_ac:
            account = int(payee['payee_account'])
            account_list = account_list.exclude(account_no=account)
        account_list = account_list.exclude(account_no=request.user.account.account_no)
        return render(request, 'money_transfer/add_payee_form.html', {'account_list': account_list})

    def post(self, request):
        user_id = int(request.POST.get('ac_id'))
        ad = AccountDetails.objects.get(id=user_id)
        account_no = ad.account_no
        ifsc = ad.ifsc_code
        PayeeDetails(payee_account=account_no, payee_ifsc=ifsc, user_id=ad.user_id).save()
        messages.success(request, 'Payee details added successfully!')
        return redirect('user_profile')

transactions/templates/money_transfer/add_payee_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
{% include "home/messages.html" %}
<h2>Add New Payee</h2><hr>
    <form method="POST" action="" id="mappingForm"  >
        {% csrf_token %}
        <table>
              <tr>
                 <th>Select Payee Accounts  and IFSC code : </th>
                 <td>
                     <select id="ac_id" name="ac_id" class="payee-dropdown" style="width:500px;">
                         <option value="" selected="">---------</option>
                         {% for al in account_list %}
                         <option value="{{ al.id }}" name="val_details">Account_No:- {{ al.account_no }} IFSC: - {{ al.ifsc_code }}</option>
                         {% endfor %}
                     </select>
                 </td>
              </tr>
        </table>
        <br>
        <input class="btn btn-primary" type="button" id="id_add" value='Add'>
        <div class="border-top pt-3">
                <small class="text-muted ml-2">
                    <b>If Payee is Added already?</b><a class="ml-2" href="{% url 'transactions:money_transfer' %}">Click here</a>
                </small>
        </div>
    </form>
{% endblock content %}

{% block script_content %}
<script>
    $("#id_add").on('click', function() {
        let selected_id = $("#ac_id").val();
        console.log(selected_id)
        if (selected_id == "" || null ) {
            alert("Please Select Payee First!")
        }
        else{
            document.getElementById("mappingForm").submit();
        }
    });
</script>
{% endblock script_content %}

transactions/templates/money_transfer/money_transfer_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
{% include "home/messages.html" %}
    <h2>Enter Payee Details</h2><hr>
    <form method="post" id="mappingForm" novalidate>
          {% csrf_token %}
          <table>
              <tr>
                 <th>Select Payee Accounts  and IFSC code : </th>
                 <td>
                     <select id="payee_id" name="payee_id" class="payee-dropdown" style="width:400px;">
                         <option value="" selected="">---------</option>
                         {{ payee_list }}
                         {% for pl in payee_list %}
                         <option value="{{ pl.id }}">Account_No:- {{ pl.payee_account }} IFSC: - {{ pl.payee_ifsc }}</option>
                         {% endfor %}
                     </select>
                 </td>
              </tr>
          </table>
          <hr>
          <input class="btn btn-primary" id="id_proceed" name="payee_id"  type="button" value='Proceed'>
        <div class="border-top pt-3">
            <small class="text-muted ml-2">
                <b>If Payee is not Added already?</b><a class="ml-2" href="{% url 'transactions:add_payee' %}">Click here</a>
            </small>
        </div>
        <div class="form-group" id="id_money" style="display:none">
            <br/>
            <label for="mode">Choose a payment mode:</label>
                <select name="mode" id="mode">
                      <option value="1"> IMPS </option>
                      <option value="2"> NEFT </option>
                </select>
            <br/>
            <br/>
            <label for="amt">Enter Amount</label>
            <input type="number" class="form-control" name="send_amt" id="id_amt" placeholder="Enter Amount" style="width:300px;">
            <hr>
            <button type="button" id="id_send"  class="btn btn-primary">Send</button>
        </div>
        <div class="form-group" id="otp_form"  style="display:none">
            <br/>
            <label for="otp_form">Enter Sent OTP on Email</label>
            <input type="number" class="form-control" name="otp" id="otp" placeholder="Enter otp" style="width:300px;">
            <small id="otpHelp" class="form-text text-muted">We'll never share your otp with anyone else.</small>
            <button type="button" id="id_submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
{% endblock content %}

{% block script_content %}
<script>
    $("#id_proceed").on('click', function() {
        let selected_id = $("#payee_id").val();
        // console.log(selected_id)
        if (selected_id == "" || null ) {
            alert("Please Select Payee First!")
        }
        else{
            $("#id_money").css("display", "block")
        }
    });
    $("#id_send").on('click', function() {
         let amt = $("#id_amt").val();
         // let otp = $(".otp_wrapper")
         if (amt<100) {
             alert("You cannot send amount less than 100.")
         }
         else{
             $.ajax({
                 url: '{% url "transactions:send_otp" %}',
                 method: "GET",
                 data: {
                     csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                 },
                 success: function (status) {
                    // console.log(status)
                 }
             });
              $("#otp_form").css("display", "block")
         }
    });
     $("#id_submit").on('click', function() {
         let otp = $("#otp").val();
         if (otp == null) {
             alert("Please Enter OTP First.")
         }
         else {
             $.ajax({
                url: '{% url "transactions:check_otp" %}',
                method: "GET",
                data: {
                    'otp':otp,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                success: function (status) {
                    // console.log(status)
                    if (status['status']== 1){
                        document.getElementById("mappingForm").submit();
                    }
                    else {
                        alert("OTP is not matching! Please Enter Correct OTP")
                    }
                }
            });
         }
     });
</script>
{% endblock script_content %}